# -*- coding: utf-8 -*-
"""feedback.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lT2ElwV3rz9bomB36Ogne6N1D8rkgII8
"""

import gradio as gr
import pandas as pd

trace_data = []

def save_feedback(index, rating, feedback_text):
    """Save user feedback to the trace data."""
    if index < len(trace_data):
        trace_data[index]["rating"] = rating
        trace_data[index]["user_feedback"] = feedback_text
        return " Feedback saved successfully!"
    return " Invalid selection!"

with gr.Blocks() as feedback_ui:
    gr.Markdown(" Provide Feedback on Chatbot Responses")

    index_slider = gr.Slider(0, len(trace_data)-1, step=1, label="Select Response")
    rating_slider = gr.Slider(1, 5, step=1, label="Rate (1 = Poor, 5 = Excellent)")
    feedback_textbox = gr.Textbox(label="Feedback", placeholder="Write your feedback here...")
    save_button = gr.Button(" Save Feedback")
    feedback_status = gr.Text()

    # Bind feedback submission
    save_button.click(save_feedback, inputs=[index_slider, rating_slider, feedback_textbox], outputs=feedback_status)

feedback_ui.launch()